image:
  name: docker/compose:latest

services:
  - docker:dind

before_script:
  - apk --update add nodejs nodejs-npm bash git openssh jq
  - npx n 12
  - docker version
  - docker-compose version
  - node -v

stages:
  - build
  - test
  - deploy

main_test:
  stage: test
  script:
    - npm install
    - npm run test
  except:
    - /^feature\/deploy.*$/
    - /^build-.*$/

deploy_to_production:
  stage: deploy
  variables:
    REPOSITORY_NAME: $CI_PROJECT_NAME
    HOSTS: trx-vnpay
  script:
    - echo temporary disable
  only:
    - /^v.*$/

deploy_to_staging:
  stage: deploy
  variables:
    REPOSITORY_NAME: $CI_PROJECT_NAME
    HOSTS: dfg-beta-cn trx-sk
  script:
    - echo temporary disable
  only:
    - master
    - /^feature\/deploy.*$/
  except:
    - /^build-.*$/

build:
  stage: build
  script:
    - version=`cat package.json | jq -r '.version'`
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$version .
    - docker images
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH:$version $CI_REGISTRY/$CI_PROJECT_PATH:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$version
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
  only:
    - tags

