# This is a basic workflow to help you get started with Actions
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 2 jobs called "build" and "deploy"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: '10' # For this issue https://github.com/grpc/grpc-node/issues/922
      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      HOSTS: trx-alpha-1 dfg-beta-cn
    steps:
      - uses: actions/checkout@v2
      - name: Run a deploy script
        run: .github/workflows/misc/deploy.sh
    needs: build
