# This is a basic workflow to help you get started with Actions
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [deploy]
  release:
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 2 jobs called "build" and "deploy"

  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      HOSTS: trx-beta-vn
    steps:
      - uses: actions/checkout@v2
      - name: Run a deploy script
        run: .github/workflows/misc/deploy.sh
